# CafeMenu CI/CD Pipeline

name: CafeMenu CI/CD Pipeline

on:
  push:
    branches: [ main, develop, release/* ]
  pull_request:
    branches: [ main, develop ]

env:
  # Solution and project paths
  SOLUTION_PATH: CafeMenu.sln
  PROJECT_PATH: CafeMenu/CafeMenu.csproj
  DOTNET_VERSION: '4.8'
  
  # Azure settings
  AZURE_WEBAPP_NAME_DEV: cafemenu-dev
  AZURE_WEBAPP_NAME_TEST: cafemenu-test
  AZURE_WEBAPP_NAME_PROD: cafemenu-prod
  AZURE_WEBAPP_PACKAGE_PATH: './published'

jobs:
  build:
    runs-on: windows-latest
    name: Build and Test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'
        
    - name: Restore NuGet packages
      run: nuget restore ${{ env.SOLUTION_PATH }}
      
    - name: Build solution
      run: msbuild ${{ env.SOLUTION_PATH }} /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
      
    - name: Run tests
      run: |
        # Add test execution here if you have unit tests
        echo "Running tests..."
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    name: Deploy to Development
    
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
    - name: Deploy to Azure Dev
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_DEV }}
        publish-profile: ${{ secrets.DEV_AZURE_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy-test:
    runs-on: ubuntu-latest
    needs: [build, deploy-dev]
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')
    name: Deploy to Test
    
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
    - name: Deploy to Azure Test
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_TEST }}
        publish-profile: ${{ secrets.TEST_AZURE_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: [build, deploy-test]
    if: github.ref == 'refs/heads/main'
    name: Deploy to Production
    
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
    - name: Deploy to Azure Production
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_PROD }}
        publish-profile: ${{ secrets.PROD_AZURE_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}